import { useState } from 'react'
import EcoPoints from '../components/EcoPoints'

export default function HomePage({ points, activities, addPoints }) {
  const [location, setLocation] = useState('')
  function locate() { setLocation('Detecting your location...'); if (!navigator.geolocation) return setLocation('Geolocation is not supported.'); navigator.geolocation.getCurrentPosition(({ coords }) => { setLocation(`${coords.latitude.toFixed(5)}, ${coords.longitude.toFixed(5)}`); addPoints(5, 'Location detected') }, () => setLocation('Unable to detect location.')) }
  const card = 'rounded-3xl bg-white p-6 shadow-lg'
  return <><section className="relative overflow-hidden px-6 pb-20 pt-14 md:pb-28 md:pt-20"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><div className="mb-6 inline-flex rounded-full border border-forest/10 bg-white/80 px-4 py-2 text-sm font-semibold text-moss">● AI-guided segregation for smarter neighborhoods</div><h1 className="max-w-3xl font-display text-5xl font-bold leading-[1.02] text-forest md:text-6xl">Waste intelligence that feels useful from the first scan.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-forest/75">Help households, campuses, and local bodies classify waste, guide recycling actions, and measure environmental impact in one confident interface.</p><a href="#complaint-form" className="mt-9 inline-block rounded-full bg-forest px-7 py-4 font-semibold text-white">Report Waste</a></div><div className="glass-panel rounded-[2rem] border border-white/80 p-5 shadow-glow"><div className="rounded-[1.7rem] bg-forest p-6 text-white"><p className="text-sm uppercase tracking-[.28em] text-lime/80">Live overview</p><h2 className="mt-2 font-display text-2xl font-bold">City Waste Command Panel</h2><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-white/10 p-5"><p className="text-sm text-white/65">Waste reports</p><p className="mt-2 text-4xl font-bold">Live</p></div><div className="rounded-3xl bg-lime p-5 text-forest"><p>Action queue</p><p className="mt-2 text-4xl font-bold">Ready</p></div></div></div></div></div></section><section id="features" className="section-grid px-6 py-20"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.28em] text-moss">Core platform</p><h2 className="mt-3 font-display text-4xl font-bold text-forest">A sharper interface for the waste management cycle.</h2></div></section><section id="citizen-services" className="px-6 py-20"><div className="mx-auto max-w-7xl"><h2 className="text-center font-display text-4xl font-bold text-forest">Smart Citizen Action Center</h2><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3"><div className={card}><h3 className="mb-4 text-xl font-bold text-forest">📍 Report Waste Location</h3><p className="mb-4 text-sm text-gray-600">Automatically detect your current location.</p><button onClick={locate} className="rounded-lg bg-forest px-4 py-2 text-white">Detect Location</button><p className="mt-4 text-sm text-forest">{location}</p></div><div className={card}><h3 className="mb-4 text-xl font-bold text-forest">📷 AI Waste Scanner</h3><p className="text-sm text-gray-600">AI classification placeholder for a future lab exercise.</p></div><EcoPoints points={points} activities={activities}/></div></div></section></>
}
