import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { getCurrentUser, login, logout, signup } from '../services/authService'

export default function Header() {
  const [user, setUser] = useState(null), [mode, setMode] = useState(null), [form, setForm] = useState({ username: '', email: '', password: '', usernameOrEmail: '' }), [error, setError] = useState('')
  useEffect(() => { getCurrentUser().then((data) => setUser(data.user)).catch(() => {}) }, [])
  async function submit(event) { event.preventDefault(); setError(''); try { const data = mode === 'login' ? await login({ usernameOrEmail: form.usernameOrEmail, password: form.password }) : await signup({ username: form.username, email: form.email, password: form.password }); setUser(data.user); setMode(null); setForm({ username: '', email: '', password: '', usernameOrEmail: '' }) } catch (requestError) { setError(requestError.response?.data?.error || 'Unable to continue. Please try again.') } }
  async function signOut() { await logout().catch(() => {}); setUser(null) }
  return <><header className="sticky top-0 z-50 border-b border-white/60 bg-sand/80 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4"><Link to="/" className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-forest text-white shadow-glow">♻</span><div><p className="font-display text-lg font-bold text-forest">SmartWasteAI</p><p className="text-xs font-medium uppercase tracking-[.28em] text-moss">Clean city intelligence</p></div></Link><nav className="hidden gap-7 text-sm font-semibold text-forest md:flex"><a href="#features">Features</a><a href="#citizen-services">Citizen Services</a><a href="#complaint-form">Report Waste</a><Link to="/complaints">Complaints</Link></nav><div className="hidden items-center gap-3 md:flex">{user ? <><span className="text-sm font-semibold text-forest">Hello, {user.username}</span><button onClick={signOut} className="rounded-full border border-forest/20 px-4 py-2 text-sm font-semibold text-forest">Logout</button></> : <><button onClick={() => setMode('login')} className="text-sm font-semibold text-forest">Login</button><button onClick={() => setMode('signup')} className="rounded-full bg-forest px-5 py-3 text-sm font-semibold text-white">Sign Up</button></>}</div></div></header>{mode && <div className="fixed inset-0 z-[100] flex items-center justify-center bg-forest/40 p-4"><div className="glass-panel relative w-full max-w-md rounded-[2rem] p-8 shadow-glow"><button onClick={() => setMode(null)} className="absolute right-6 top-4 text-2xl text-forest">×</button><h2 className="font-display text-3xl font-bold text-forest">{mode === 'login' ? 'Welcome back' : 'Create account'}</h2><form onSubmit={submit} className="mt-6 space-y-4">{mode === 'signup' && <><input required placeholder="Username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })} className="w-full rounded-lg border p-3"/><input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="w-full rounded-lg border p-3"/></>}{mode === 'login' && <input required placeholder="Username or email" value={form.usernameOrEmail} onChange={(e) => setForm({ ...form, usernameOrEmail: e.target.value })} className="w-full rounded-lg border p-3"/>}<input required minLength="6" type="password" placeholder="Password" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} className="w-full rounded-lg border p-3"/>{error && <p className="text-sm text-red-600">{error}</p>}<button className="w-full rounded-lg bg-forest px-6 py-3 font-semibold text-white">{mode === 'login' ? 'Login' : 'Sign Up'}</button></form></div></div>}</>
}
